export default {

    IZINLI_KISILER: ["IZINLI_KISI_ID", "IZINLI_KISI_ID_2", "BU_SEKILDE_UZATABILIRSINIZ"],
    // BOT KOMUTLARINI KULLANABILECEK KISILERDIR. YANINA BIR , BIRAKIP "" ACARAK UZATABILIRSINIZ

    BOT_TOKEN: "",
    // DISCORD BOTUNUZUN TOKENINI UST KISMA GIRIN

    TESLIM_HESAPLARI: ["HESAP_1_TOKEN", "HESAP_2_TOKEN", "HESAP_3_TOKEN", "HESAP_4_TOKEN", "MAKSIMUM_25_HESAP_TOKENI_GIREBILIRSINIZ"],
    // TESLIM HESAPLARINI YUKARIDAKI GIBI YANINDA BIR , BIRAKIP "" ACARAK GIREBILIRSINIZ (MAX 25 HESAP GIREBILIRSINIZ)

    WEBHOOK_URL: "",
    // KULLANICININ KODU KULLANACAGI KANALDA BIR WEBHOOK OLUSTURUN VE URL'SINI UST KISMA GIRIN

    SUNUCU_ID: "", // TESLIM SUNUCUNUZUN ID'SI
    OWO_TESLIM_KANALI_ID: "", // OWO PARASININ TESLIM EDILECEGI KANAL (BU KANALI ALICI GORMEMELIDIR)
    LOG_KANALI_ID: "", // LOGLARIN TUTULACAĞI KANAL ID

    KICK_TIME: "1", // KULLANICI SUNUCUDAN 1 DAKIKA ICINDE ATILIR
    OWO_BOT_ID: "408785106942164992", // ORJİNAL OWO BOTUNUN ID'SI (DEGISTIRMEYIN!)
    PREFIX: [".", "!"], // DEGISTIRMENIZE GEREK YOK
    TESLIM_MESAJI: "owo give {user} {cash}", // DEGISTIRMENIZE GEREK YOK
    WEBHOOK_TESLIM_MESAJI: "OwO paranız başka bir kanal üzerinden gönderildi. Lütfen gelip gelmediğini **owo cash** yazarak kontrol edin!", // DEGISTIRILEBILIR
    WEBHOOK_HATA_MESAJI: "OwO paranız şu anda teslim edilemiyor, lütfen satıcınıza danışın!" // DEGISTIRILEBILIR

}